### ISSUE TITLE
No puedo enviar mensaje en Contacto

### ISSUE THREAD

**Issue by jforni** [FranprzDev/LaburandoAndo#112]
Cuando quiero enviar un mensaje en la sección de Contacto, no me deja enviarlo y me muestra un mensaje de error "Ingrese un mensaje válido". 
Adjunto imagen de muestra:
![image](https://github.com/user-attachments/assets/962d3728-1a8a-4ad7-b220-43306459c709)

**Comment by Juliancito1** [comment]
Solucionado, faltaban agregar el uso de puntos, comas y acentos en la expresión regular
