### ISSUE TITLE
Mejorar un poco los estilos de la card de trabajos. 

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#24]
Dejar el CSS pipi cucú.

Cree un campo llamado 'outstanding' que sirve para saber quienes son destacados y quienes no (vamos a implementar una pequeña lógica de negocios; diciendo que para mantener la aplicación a flote haremos que quienes quieran salir arriba deben pagar).
Además también implementaremos un filtro para los destacados.

Cuando el outstanding este en false; lo que es la foto debe ocupar el 100% de su cuadrícula.
![image](https://github.com/user-attachments/assets/d42fadd8-8da6-4982-825a-2031b57c0c37)

Cuando el outstanding este en true debe quedar como está ahora, se podría repensar el 'destacado' como si fuese otro borde tal vez, así no modifque en nada y el tamaño de todas las cards sea igual.

**Comment by FranprzDev** [comment]
También estaría bueno acomodar las valoraciones para que queden todas okey; me gusta mucho como quedan en tamaños pequeños; pero no me termina de convencer que esté el "10" y abajo el valor "valoraciones".
Esto hace que quede, muy raro, si es muy difícil de acomodar podríamos directamente quitar ese campo.

**Comment by brunomry** [comment]
![Uploading card correccion.jpg…]()

**Comment by brunomry** [comment]
![card correccion](https://github.com/user-attachments/assets/c8fa7204-2ba2-47be-839d-f25095783587)

se corrigió la card para que la parte de "valoraciones" se vea en la misma linea el numero y la palabra valoraciones
la parte de destacado se mantiene oculta por el momento, se editará nuevamente cuando se tenga la lógica

**Comment by brunomry** [comment]
![card](https://github.com/user-attachments/assets/91babd57-6b81-40e6-8306-ecd29ea81865)

en dispositivos moviles se agregó nuevamente el boton de la card para redirigir al detalle
