### ISSUE TITLE
Posibilidad en pantallas chicas de esconder los filtros. [Low]

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#25]
Estaría bueno tener un '<' (hacia abajo) que permita esconder los filtros cuando nos encontramos en pantallas pequeñas.

![image](https://github.com/user-attachments/assets/85aeb95e-345d-4db8-8e9c-92ef492df393)

**Comment by brunomry** [comment]
![filters](https://github.com/user-attachments/assets/724caf20-8d0d-4fc6-a337-60684d8f29ce)

se disminuyó un poco la altura de los filtros por cambio de campo de categorias y disminuyendo margen inferior de labels

**Comment by brunomry** [comment]
![filters2](https://github.com/user-attachments/assets/9eaa6484-bf2e-4768-b40f-61c13e5455c4)

agregue los filtros de pagina profesionales dentro de un acordion de react-bootstrap para poder ocultarlos en dispositivos moviles
