### ISSUE TITLE
Componente FAQ; funcionalidad

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#27]
En el componente donde se muestran los faqs hay que poner cosas más específicas de lo que estamos trabajando (generado con chatgpt por ejemplo) y hay que corregir que se puedan cerrar y abrir los FAQS, así no queden todos abiertos; podríamos también cambiar el color
![image](https://github.com/user-attachments/assets/b6f1995b-5935-4384-91fd-2df5b334d5ed)

**Comment by brunomry** [comment]
![faq](https://github.com/user-attachments/assets/12944da4-a6c0-4e1c-befd-8c93e584b972)

se modificó estilos de acordión y se corrigió para que se cierre cada pregunta al clickear en otra

**Comment by brunomry** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/5ce3e944-0b6b-406b-9604-ad3e94ac6931)

Visualización de respuesta
