### ISSUE TITLE
RegisterPaso2

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#28]
Parte de maquetado, alinear el texto cuando está en responsive que queda feo si no.

**Comment by FranprzDev** [comment]
![image](https://github.com/user-attachments/assets/269d13e9-a7f5-4630-8b2a-a718c26d587d)

**Comment by brunomry** [comment]
se agregó clase order para que el form aparezca primero en celus

![r2 celus](https://github.com/user-attachments/assets/85e57b38-929f-4dbc-839b-cb74da9e0ff1)

se agregó texto descriptivo para usuario cliente

![r2](https://github.com/user-attachments/assets/be2e47d4-95b0-463e-bd0a-8e79f38fba4d)

**Comment by brunomry** [comment]
se alineó el texto descriptivo para ambos usuarios
