### ISSUE TITLE
Corregir Responsive de Register Paso 3

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#29]
Se rompe el responsive aquí en pantallas pequeñas..

![image](https://github.com/user-attachments/assets/6885c2a9-e38f-4525-b81e-0918fe78d79a)

**Comment by FranprzDev** [comment]
![image](https://github.com/user-attachments/assets/173276e9-b7ee-4fc7-93c2-3cb643089338)
Este responsive cuando está chiquito, me gustaría que no se pegue del todo, cuando está grande quedaría así. Lo modifiqué un poco.
Hay que poner todo alineado; es decir lo que son el icono - whatsapp - opcional hay que alinearlo..

Evaluar si dejar el "opcional" o poner otra cosa, podemos pone un tooltip por ejemplo.
Eso lo dejo en improve.

**Comment by brunomry** [comment]
en celus

![r3 celus](https://github.com/user-attachments/assets/a74649dc-9475-4444-b23b-a6e670b74d0a)

en tablet

![r3 tablet](https://github.com/user-attachments/assets/675a687c-e912-498b-bd1d-fde448196291)

en pc

![r3 desktop](https://github.com/user-attachments/assets/2bb481a5-339c-4d5a-a2d1-34c4781c9da3)

se aplicó responsividad en todos los dispositivos, se alineó iconos con label, se agrego tamaño al form y otros estilos
