### ISSUE TITLE
Al hacer Click en el Register Paso 1, el botón se vuelve blanco e ilegible.

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#30]
![image](https://github.com/user-attachments/assets/4ae5df7e-a86e-4c09-8156-33da63606e58)

Esto tiene que ver con las : de bootstrap por defecto, se pueden fijar; en mi componente register paso 2; donde ahí le hice el cambio en el .css.

**Comment by brunomry** [comment]
esto ya estaba corregido!
