### ISSUE TITLE
En tamaño mediano, el footer no se pega abajo de la página

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#32]
![image](https://github.com/user-attachments/assets/4700e30a-7380-490b-a868-a11bc2daa355)

**Comment by brunomry** [comment]
![registro paso 3](https://github.com/user-attachments/assets/358f548c-67de-4d07-9ba2-3fe6cf967b18)

se corrigió en pagina registro paso 3 para que el footer se quede abajo en todos los dispositivos
