### ISSUE TITLE
Agregar un breadcrum para poder ubicarse donde estamos en la aplicación

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#34]
Hay que cambiar eso, que queda muy feo así no más.
Un breadcrum común tipo
Personita > Mi perfil 
Personita > Publicar Anuncio
Personita > Mis publicaciones
![image](https://github.com/user-attachments/assets/bb67dcb3-49c2-471f-bc15-f614e8b80770)

**Comment by brunomry** [comment]
![bread](https://github.com/user-attachments/assets/bc3073e9-52dd-4446-9c13-f9ab8c402d8f)

se agregó breadcrumb para paginas mi perfil y publiccacion de anuncio
