### ISSUE TITLE
work/mi-perfil Hacer que todos estén alineados al mismo lugar

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#35]
Queda raro que el salir este muy lejos.
También; hay que generar un conceso acerca de la url /mi-perfil
Sugeriría ver si podemos dejarlo en default /work/ 

Opinar aquí: 
![image](https://github.com/user-attachments/assets/e7fae882-c7a2-4624-8fee-515c949464b6)

**Comment by brunomry** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/e0e52a69-59f8-4cd5-b587-fef73bac88d3)

se alineó opcion Salir
