### ISSUE TITLE
Cambiar el LaburandoAndo

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#36]
Creo que estamos quemando la marca, lo ponemos muchas veces y no le veo tanto sentido decirlo muchas veces, por que ya se sabe.
Buscaría intentar poner algo característico, podríamos intentar poner algo así como un icono de palita.
![image](https://github.com/user-attachments/assets/150eb500-2bf5-4d58-97c3-561e336a584e)

**Comment by FranprzDev** [comment]
Quite el 'Home' de ahí, por que me parecía medio tonto tenerlo, ya que no afecta en nada.

Evaluen la posiblidad de que al tocar el logito en vez de llevarte a la página home, directamente te pida hacer un logout.

**Comment by brunomry** [comment]
Cambie el tamaño de la letra de LaburandoAndo en 30px y lo quité de donde no hacía falta para que no se repita tanto
