### ISSUE TITLE
Cambiar la forma de editar los datos del profesional.

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#37]
Me gustaría que en vez de un botón, sea un icono, puede ser un pencil para editar; además también daremos la posibilidad de dar de baja una cuenta, pero para esto podríamos o habilitar un endpoint en el menú lateral o podríamos agregarlo ahí.
Queda a decisión de quien agarre la tarjeta; lo que si pediré si el editar de la foto puede ser como los demás.
Para esto, pueden usar el css de registerPasoTres que añade un botoncito de tipo input y que queda muy fachero.
Este botoncito DEBE estar deshabilitado cuando no se quite el botoncito del pencil; además me gustaría que exista un botón para volver a los valores anteriores; si se complica trabajar con esto, hacen solamente lo del botoncito de editar, el botoncito de eliminar y dejan hecho un botoncito de reset y después lo agrego yo, no tiene mucha prioridad.

![image](https://github.com/user-attachments/assets/5b7fc7dc-783b-414c-8eb4-a3cc2a651a52)

La idea sería basarnos y que nos queden todos los inputs de imagenes casi que iguales.
![image](https://github.com/user-attachments/assets/78366706-5da7-47a1-8296-d27f9f747713)

**Comment by brunomry** [comment]
Se agrego misma estructura para campo imagen de perfil tomando los estilos usados de registro paso 3

![edit2](https://github.com/user-attachments/assets/e61f5a21-47df-4211-b7a0-5855f7587556)
![editprofile](https://github.com/user-attachments/assets/8c737764-dd05-4692-8141-50872d02774e)
