### ISSUE TITLE
Refactorizar el código / Cambiar estructura del proyecto.

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#41]
Hay que cambiar las carpetas, las ubicaciones y demás; por que la realidad es que está un re quilombo.

Si el proyecto crece un poco más de lo que estamos pensando, próximamente esto será bastante complicado, estamos a tiempo.

**Comment by brunomry** [comment]
Modifique la estructura del proyecto al tipo de estructura basada en dominios

![Screenshot_7](https://github.com/user-attachments/assets/4d5caaee-ccd0-402b-ba81-d419e1775a86)

**Comment by brunomry** [comment]
![Screenshot_8](https://github.com/user-attachments/assets/8875aab7-34fa-44e6-8adc-9bfd7d4486ce)
