### ISSUE TITLE
Esto se rompe cuando el texto es muy largo 

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#44]
![image](https://github.com/user-attachments/assets/9b995f11-f0ad-4d08-8de1-47e2311d0797)

**Comment by brunomry** [comment]
Solucionado mediante propiedades css para que el texto no desborde de su contenedor

![card](https://github.com/user-attachments/assets/61331b84-1a42-49fc-bcc8-296ded165e14)
