### ISSUE TITLE
Refactorizar el useEffect a otros Componentes.

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#46]
Los componentes de modales, se renderizan por medio de useEffects.
Estos useEffects, habría que pasarlos a la carpeta así:
![image](https://github.com/user-attachments/assets/ac7f767e-cb47-4676-aa08-4bf3b7839355)

Y que quede de la siguiente manera:
![image](https://github.com/user-attachments/assets/e4cad1e2-0510-4531-af0c-bde9fda544b5)

El componente JSX, y se lo llama de la siguiente forma, así reducimos el código y sea más legible.
![image](https://github.com/user-attachments/assets/8ddcda4c-203c-4407-9a7c-86ed29d71863)

**Comment by Juliancito1** [comment]
Esta función quedo sin uso y fue eliminada por una mejor
