### ISSUE TITLE
Cambiar la barra de dseplazamiento

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#54]
Cambiar la barra de desplazamiento, hará que nuestra marca sea más linda, y se vea mejor la página.
![image](https://github.com/user-attachments/assets/39bf1094-4f6b-42af-884b-87dc203d760f)

Me refiero a esa.

**Comment by brunomry** [comment]
agregue los estilos para el scroll en app.css en pr de read publicaciones profesional
