### ISSUE TITLE
Arreglar el footer 

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#7]
El footer se rompe, la parte de 'LaburandoAndo' queda medio raro.
La prioridad la verdad es que es muy baja, pero se tomará en este sprint esta tarea para que quede bien.
![image](https://github.com/user-attachments/assets/0c5e018c-6b12-4604-96ac-c4d91b69e7f6)

**Comment by brunomry** [comment]
se corrigió tamaño de logo y se corrigieron estilos del footer para que ya no se rompa en ningun dispositivo

**Comment by brunomry** [comment]
![footer lg](https://github.com/user-attachments/assets/6082ecd5-bb92-444c-9e08-ec4658ec3cc0)
