### ISSUE TITLE
Revisar el tema de filtros.

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#74]
Revisar como se comporta en 'md' estaría bueno que este en la mitad de la pantalla.
![image](https://github.com/user-attachments/assets/46b2ad83-1755-4ca4-bf68-f4d5aeab7be4)

**Comment by FranprzDev** [comment]
![image](https://github.com/user-attachments/assets/5e5f1780-12e0-4e52-a9ef-0b24e744b5ba)
![image](https://github.com/user-attachments/assets/045a90ce-9ecf-4594-9660-3bc675697840)

Cuando estoy en pantallas chiquitas, y lo acomodo queda muy chombi.
Habría que intentar que mantenga el mismo tamaño.

**Comment by FranprzDev** [comment]
![image](https://github.com/user-attachments/assets/ab2daaca-8952-4314-943f-de097add8a60)
No me terminan de convencer los botones estos; para cambiar, pero lo dejo a votación del grupo para ver si les gusta o no, a mí en personal los cambiaría tal vez hacia algo más redondo.

**Comment by brunomry** [comment]
corregido los filtros centrados en md, se agregó clase w-100 a acordión (antes estaba)
