### ISSUE TITLE
Acomodar el responsive de la Card del Profesional.

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#75]
La parte de las card y las valoraciones.
![image](https://github.com/user-attachments/assets/01bcc079-9bd6-4056-8431-ca83718fe7b8)

**Comment by brunomry** [comment]
Se corrigió altura de imagen y texto de valoraciones para que aparezca en una linea

![card](https://github.com/user-attachments/assets/16a7943e-0918-43fe-9152-4607baddb0b2)
