### ISSUE TITLE
Se rompe el titulo de 'LaburandoAndo'

### ISSUE THREAD

**Issue by FranprzDev** [FranprzDev/LaburandoAndo#94]
820px
![image](https://github.com/user-attachments/assets/f266bc09-c96c-4632-9841-50c027c320c2)

**Comment by FranprzDev** [comment]
Esto solo se produce cuando lo movemos con las opciones del desarrollador, quien vea si es mucho lío directamente pueden decidir si ignorar esto y cerrarlo con el comentario, no es algo esencial.

**Comment by brunomry** [comment]
Corroborar en otros navegadores, en brave por ejemplo no se rompe
